/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Window;


import Class.Global;
import Class.Constant;
/**
 *
 * @author Juliana
 */
public class LevelSelectionWindow extends javax.swing.JFrame {

    /**
     * Creates new form LevelSelectionWindow
     */
    public LevelSelectionWindow() {
        initComponents();
        
        this.setTitle("Level Selection");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        
        Global.actualizeGlobal();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonEasyLevel = new javax.swing.JButton();
        buttonMediumLevel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buttonHardLevel1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Window/HightLevel.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 220, 160));

        buttonEasyLevel.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        buttonEasyLevel.setForeground(new java.awt.Color(255, 255, 255));
        buttonEasyLevel.setText("Easy");
        buttonEasyLevel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        buttonEasyLevel.setContentAreaFilled(false);
        buttonEasyLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEasyLevelActionPerformed(evt);
            }
        });
        getContentPane().add(buttonEasyLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 180, 40));

        buttonMediumLevel.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        buttonMediumLevel.setForeground(new java.awt.Color(255, 255, 255));
        buttonMediumLevel.setText("Medium");
        buttonMediumLevel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        buttonMediumLevel.setContentAreaFilled(false);
        buttonMediumLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMediumLevelActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMediumLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 180, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Window/LowLevel.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 230, 170));

        buttonHardLevel1.setBackground(new java.awt.Color(255, 255, 255));
        buttonHardLevel1.setFont(new java.awt.Font("Segoe UI Black", 1, 30)); // NOI18N
        buttonHardLevel1.setForeground(new java.awt.Color(255, 255, 255));
        buttonHardLevel1.setText("Hard");
        buttonHardLevel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        buttonHardLevel1.setContentAreaFilled(false);
        buttonHardLevel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHardLevel1ActionPerformed(evt);
            }
        });
        getContentPane().add(buttonHardLevel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 180, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Window/MediumLevel.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(291, 129, 230, 170));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Window/LevelSelectionImage.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Window/imageBlack.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 530));

        jMenu1.setText("File");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Window/BackImage.jpg"))); // NOI18N
        jMenuItem1.setText("Back");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void loadingGameWindow(){
        GameWindow window = new GameWindow();
        window.setVisible(true);
        this.dispose();        
    }
    
    private void buttonMediumLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMediumLevelActionPerformed
        // TODO add your handling code here:
        
        Global.setLevelOfTheGame("Medium");
        Global.setAmountBalloon(8);
        Global.setAmountBarrel(5);
        Global.setAmountMatrix(21); 
        Global.setAmountBlock(75);
        Global.setAmountPower(2);
        Global.setLevelOfTheBomb(Constant.DEFAULT_POWER_OF_THE_BOMB);
        loadingGameWindow();

    }//GEN-LAST:event_buttonMediumLevelActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        PrincipalWindow window = new PrincipalWindow();
        window.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void buttonEasyLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEasyLevelActionPerformed
        // TODO add your handling code here:
                
        Global.setLevelOfTheGame("Easy");
        Global.setAmountBalloon(5);
        Global.setAmountBarrel(3);
        
        Global.setAmountMatrix(15); 
        
        Global.setAmountBlock(35);
        Global.setAmountPower(3);
        
        Global.setLevelOfTheBomb(Constant.DEFAULT_POWER_OF_THE_BOMB);
        loadingGameWindow();
        
        
    }//GEN-LAST:event_buttonEasyLevelActionPerformed

    private void buttonHardLevel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHardLevel1ActionPerformed
        // TODO add your handling code here:

        Global.setLevelOfTheGame("Hard");
        Global.setAmountBalloon(12);
        Global.setAmountBarrel(10);
        
        Global.setAmountMatrix(25); 
        System.out.println("matrix es de "+ Global.getAmountMatrix());
        
        Global.setAmountBlock(120);
        Global.setAmountPower(1);
        Global.setLevelOfTheBomb(Constant.DEFAULT_POWER_OF_THE_BOMB);
        loadingGameWindow();


    }//GEN-LAST:event_buttonHardLevel1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LevelSelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LevelSelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LevelSelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LevelSelectionWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LevelSelectionWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEasyLevel;
    private javax.swing.JButton buttonHardLevel1;
    private javax.swing.JButton buttonMediumLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables
}
